/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Tokens whose value differs between the desktop and mobile themes are
        // driven by CSS variables defined in src/index.css. Variables hold
        // space-separated RGB channels so Tailwind's /opacity modifiers
        // (e.g. bg-surface/80) keep working. Fixed tokens stay as literals.
        'surface': 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': 'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'outline': 'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',
        'surface-tint': '#3b5e97',
        'primary': 'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary': '#ffffff',
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'inverse-primary': '#aac7ff',
        'secondary': '#555f71',
        'on-secondary': '#ffffff',
        'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        'tertiary': '#6c5000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#89670b',
        'on-tertiary-container': '#ffedcf',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#aac7ff',
        'on-primary-fixed': '#001b3e',
        'on-primary-fixed-variant': '#20467e',
        'secondary-fixed': '#d9e3f9',
        'secondary-fixed-dim': '#bdc7dc',
        'on-secondary-fixed': '#121c2c',
        'on-secondary-fixed-variant': '#3d4759',
        'tertiary-fixed': '#ffdf9e',
        'tertiary-fixed-dim': '#ecc161',
        'on-tertiary-fixed': '#261a00',
        'on-tertiary-fixed-variant': '#5b4300',
        'background': '#f7f9fb',
        'on-background': '#191c1e',
        'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'unit': '4px',
        'gutter': '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'display': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
